@startuml
Node -> Chef : ask for runlist
Chef -> Node : sends runlist and node's attributes
Node -> ForemanProxy : ask for ENC yaml
hnote over ForemanProxy : authentication
ForemanProxy -> Foreman : get ENC for Node
Foreman -> ForemanProxy : ENC yaml
ForemanProxy -> Node : ENC yaml
hnote over Node : Merge attributes from Chef and Foreman ENC
== Chef-client coverges ==
Node -> ForemanProxy : upload facts
hnote over ForemanProxy : authentication
ForemanProxy -> Foreman : forwards facts
Node -> ForemanProxy : upload report
hnote over ForemanProxy : authentication
ForemanProxy -> Foreman : upload report
@enduml
