#!/bin/bash

for VERSION in nightly 3.1; do
	NAME=foreman-manual-$VERSION
	scripts/to_singlepage.rb $VERSION > $NAME.md
	pandoc -f markdown-smart-emoji -t asciidoc --wrap=preserve $NAME.md > $NAME.adoc
	asciidoctor $NAME.adoc
done
